plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
remote_theme: "pages-themes/primer"
title: "Livelli essenziali di assistenza (LEA): le nostre richieste essenziali"
description: La tutela della salute è un diritto dell'individuo, per questa ragione facciamo delle richieste sui LEA
lang: it-IT
